name: "Hello GitHub Actions"
description: "Greet someone"
author: "me"

input:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
   
 runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
