name: A workflow for my Hello World fiile
on: push

jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Luis"
